name: Dependabot auto-merge
on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
      - name: Auto-merge dependabot pull request
        run: gh pr merge --auto --squash "${PR_URL}" --repo ${{ github.repository }}
        env:
          PR_URL: ${{github.event.workflow_run.pull_requests[0].url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
